**Question** -make a 100X100 array which has each of it's element as 2.

In [1]:
import numpy as np

In [8]:
x=np.zeros((1,100))
y=x.reshape(10,10)

In [9]:
z=y+2

In [10]:
z

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

**Question**- Suppose we have any array [0.12,0.47,0.64,0.87,0.96] how can we convert this array to [12.12,12.47,12.64,12.87,12.96]

In [13]:
a=np.random.rand(4)
a

array([0.66097012, 0.76232147, 0.53527216, 0.25628062])

In [14]:
b=a+12
b

array([12.66097012, 12.76232147, 12.53527216, 12.25628062])

**Question**-Explain the functionality of the following

**1) Tile**

syntax : np.tile(name of array, repetitions) 

In [20]:
# let us construct an array named p
p= np.arange(1,6)
#now using the tile function we can construct a new array by  repetitions of array p by specifing the number of repetitions.
np.tile(p, 50)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1,
       2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3,
       4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
       1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4,
       5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1,
       2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3,
       4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5,
       1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5, 1, 2, 3, 4, 5])

**2)Diag**

syntax: np.diag(a, k=0) 

Extracts or construct a diagonal array


In [29]:
q=np.eye(3,3)
q

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#extracting a diagonal array from a given array
np.diag(q)

array([1., 1., 1.])

In [35]:
#constructing an array
n=np.array([56,87,90,45,66,100])
n

array([ 56,  87,  90,  45,  66, 100])

In [37]:
np.diag(n)

array([[ 56,   0,   0,   0,   0,   0],
       [  0,  87,   0,   0,   0,   0],
       [  0,   0,  90,   0,   0,   0],
       [  0,   0,   0,  45,   0,   0],
       [  0,   0,   0,   0,  66,   0],
       [  0,   0,   0,   0,   0, 100]])

**3)Inverse**

Syntax : numpy.linalg.inv(a)

Finds the inverse of a square matrix


In [53]:
h = np.array([[1,0,-2],[3,1,-2],[-5,-1,9]]) 
h

array([[ 1,  0, -2],
       [ 3,  1, -2],
       [-5, -1,  9]])

In [54]:
i= np.linalg.inv(h) 
i

array([[ 2.33333333,  0.66666667,  0.66666667],
       [-5.66666667, -0.33333333, -1.33333333],
       [ 0.66666667,  0.33333333,  0.33333333]])

**4)Transpose**

Syntax : name_of_matrix.transpose(*axes)

Returns a view of the array with axes transposed.

For a 1-D array, this has no effect. (To change between column and row vectors, first cast the 1-D array into a matrix object.) For a 2-D array, this is the usual matrix transpose. 

In [41]:
a = np.array([[1, 2,4,5,5,7,9], [3, 4,7,9,3,5,8],[3,4,5,6,7,6,5],[4,5,6,7,8,7,8]])
a

array([[1, 2, 4, 5, 5, 7, 9],
       [3, 4, 7, 9, 3, 5, 8],
       [3, 4, 5, 6, 7, 6, 5],
       [4, 5, 6, 7, 8, 7, 8]])

In [43]:
a.transpose()

array([[1, 3, 3, 4],
       [2, 4, 4, 5],
       [4, 7, 5, 6],
       [5, 9, 6, 7],
       [5, 3, 7, 8],
       [7, 5, 6, 7],
       [9, 8, 5, 8]])

**Question** -Module v/s Library

**LIBRARY**

Python library is a collection of functions and methods that allows you to perform lots of actions without writing your own code. 
For example- if you are working with data, *numpy, pandas,* etc. are some useful libraries .

**MODULE**

A module is a file containing Python definitions and statements. A module can define functions, classes and variables. A module can also include runnable code. Grouping related code into a module makes the code easier to understand and use.

*1)here is an example of a **simple module**  one created by the user.*

Let us create a module.

In [58]:
#Here's an example of a simple module
def hello( par ):
    a="Hello : "+ par
    return a

*2)You can use any Python source file as a module by executing an** import** statement in some other Python source file.For example, to import the module support.py, we need to put the following command at the top of the script −*

In [ ]:
# Import module support
import support

# Now you can call defined function that module as follows
support.hello("Zara")

*3)Python’s **from... import** statement lets you import specific attributes from a module.*

In [ ]:
# let statistics is a module for finding statistical values 
from statistics import mean,median,var,mode
  
# if we simply do "import statistics", then 
# statistics.mean() , statistics.median() ,statistics.mode()etc are required but now 
print mean([1,2,4]) 
print median([12,34,67,89]) 
print mode([12,34,67,89]) 
print var(90)

**Question **- Why everything in Python is an object?


In Python everything is an object: every integer, string, list, and function. What we might think of as a variable, instead think of it as a name.
Python is using a pure object model where classes are instances of a meta-class “type” (in Python, the terms “type” and “class” are synonyms). And “type” is the only class which is an instance of itself
This object model can be useful when we want information about a particular resource in Python. Except for the Python keywords (e.g. if, def, globals), using "type()"

**Question** Why is np.newaxis used ?

The np.newaxis is used to add one dimension to the  existing array, when used once.Thus, **N-D array will become (N+1)-D array**

In [78]:
x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([5, 4, 3])

In [80]:
x1.shape

(5,)

In [72]:
# now, the shape of x1_new is (5, 1)
x1_new = x1[:, np.newaxis] 

In [73]:
x1_new 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [74]:
x1_new + x2

array([[ 6,  5,  4],
       [ 7,  6,  5],
       [ 8,  7,  6],
       [ 9,  8,  7],
       [10,  9,  8]])